### ISSUE TITLE
Working with in-browser disabled third-party cookies

### ISSUE THREAD

**Issue by FarSeeing** [contently/xdomain-cookies#2]
Hi.

I'm a newbie with your library. The readme says it should work even if user disabled third-party cookies in the browser. I'm trying to re-create that with the example provided in the repository. So I run `npm run dev`, make sure third-party cookies are disabled, navigate to `http://shared_cookie_test.com:3001/test_page.html` in one tab and then to `http://shared_cookie_test2.com:3001/test_page.html` in another.
The console on the first page outputs

```
test_page.html:39 COOKIE VAL RETURN:  null
test_page.html:45 SETTING EMPTY COOKIE set_from:shared_cookie_test.com:3001
test_page.html:52 COOKIE VAL RETURN AFTER SET: set_from:shared_cookie_test.com:3001
```

The console on the second page outputs

```
COOKIE VAL RETURN:  null
test_page.html:45 SETTING EMPTY COOKIE set_from:shared_cookie_test2.com:3001
test_page.html:52 COOKIE VAL RETURN AFTER SET: set_from:shared_cookie_test2.com:3001
```

After reloading the console on the first page ouputs

```
test_page.html:39 COOKIE VAL RETURN:  set_from:shared_cookie_test.com:3001
```

and on the second

```
test_page.html:39 COOKIE VAL RETURN:  set_from:shared_cookie_test2.com:3001
```

I guess that should not happen. Browser - Chrome 53.0.2785.116, OS - Windows 8.1 Pro x64.

**Comment by FarSeeing** [comment]
Any ideas?

**Comment by yshaool** [comment]
From Readme:
Limitations
Due to how browsers handle, and what they consider 3rd-party cookies/data, if a browser is set to disable 3rd-party cookies this library will not function. This is because, regardless of the actual site the cookie is being set on, the top-level source domain must match the domain of internal frames for cookies to be considered 1st-party. Browsers do this for security concerns, and there is, unfortunately, no way around this based on current browser functionality.

**Comment by FarSeeing** [comment]
Yes, right, the README was [updated](https://github.com/contently/xdomain-cookies/commit/0ae368fc93d15bd9278c32b3e6fb122e25bf7191) after I sent this issue.
Guess it's not actual anymore.
